# Generated by Django 5.2.10 on 2026-01-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioEscolar',
            fields=[
                ('id_anio_escolar', models.AutoField(primary_key=True, serialize=False)),
                ('anio_escolar', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anio_escolar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('talla_camisa', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_pantalon', models.CharField(blank=True, max_length=10, null=True)),
                ('talla_zapato', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'estudiante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'grado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('anio_ingreso', models.IntegerField()),
                ('fecha_matricula', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'matricula',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'representante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'turno',
                'managed': True,
            },
        ),
    ]
