# Generated by Django 5.2.10 on 2026-02-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anioescolar',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='representante',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'managed': True},
        ),
    ]
